version: '3.7'

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: $POSTGRES_NAME
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    restart: always
    ports:
      - '5432:5432'
    networks:
      - rosatom-sso-network
    volumes:
      - ./migrations/postgres/versions/001.sql:/docker-entrypoint-initdb.d/001.sql
      - pgdata:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: bitnami/redis:latest
    environment:
      REDIS_PASSWORD: $REDIS_PASSWORD
    restart: always
    ports:
      - '6379:6379'
    networks:
      - rosatom-sso-network

  telegram-bot:
    container_name: rosatom-sso-bot
    build:
      context: .
      target: production
    restart: always
    networks:
      - rosatom-sso-network
    env_file:
      - '.env'
    volumes:
      - ./rosatom_sso:/rosatom-sso/rosatom_sso
      - ./migrations:/rosatom-sso/migrations
      - ./logs:/rosatom-sso/logs
    depends_on:
      - postgres
      - redis

volumes:
  pgdata:

networks:
  rosatom-sso-network:
    driver: bridge